version: '3.7'

services:

  api:
    build: .
    image: computations/app:latest
    command: api
    env_file: ./env.staging
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq

  worker-machine1:
    image: computations/app:latest
    command: worker --concurrency 2
    env_file: ./env.staging
    depends_on:
      - postgres
      - rabbitmq

  worker-machine2:
    image: computations/app:latest
    command: worker --concurrency 2
    env_file: ./env.staging
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    build:
      context: ./dockerfiles/postgres
    image: computations/postgres:12.4-alpine
    ports:
      - 5432:5432

  rabbitmq:
    build:
      context: ./dockerfiles/rabbitmq
    image: computations/rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    ports:
      - 4369:4369
      - 5671-5672:5671-5672
      - 15671-15672:15671-15672
      - 15691-15692:15691-15692
      - 25672:25672
